### ISSUE TITLE
useState within an existing hook (useEffect)

### ISSUE THREAD

**Issue by jgentes** [teafuljs/teaful#100]
**What version of this package are you using?** 
0.11.1

**What problem do you want to solve?** 
Subscription (event listener / observer) without a hook.. here's the scenario:

Within a React functional component, I have a `useEffect` hook which performs an expensive operation, then I use the result for a variety of other things, such as in this example of baking a cookie, then eating it:

```js
const CookieComponent = () => {

  useEffect(() => {
    let cookie
    const bakeCookie = async () => cookie = await bake('cookie')
    bakeCookie()

    // this is where I want teaful to watch for activity
    function eatCookie() {
      const [milk] = teafulState.milk()
     
      if (milk) eat(cookie)

       // I can do this instead: window.addEventListener('milk', () => eat(cookie))
    }
}
```

I'm trying to use teaful to replace my event bus, however I can't seem to use the subscriptions within a hook, where I currently use listeners.

**What do you think is the correct solution to this problem?** 
Not sure, something like `window.addEventListener`?

**Are you willing to submit a pull request to implement this change?**
Yes, if I knew what needed to be done.

Thanks! Great state management tool :)

**Comment by aralroca** [comment]
@jgentes was this solved?

**Comment by jgentes** [comment]
No, but I found an alternate way to get rid of my event emitters. I'm using teaful, just not in the useEffect hook like I mentioned here.
