### ISSUE TITLE
Ask a question goes to StandardJS

### ISSUE THREAD

**Issue by jgentes** [teafuljs/teaful#101]
Your 'Ask a question' link on Github issues goes to StandardJS: https://github.com/teafuljs/teaful/issues/new/choose

It links here: https://discord.gg/ZegqCBr

Oops!

**Comment by aralroca** [comment]
Good catch! We need to change the URL here https://github.com/teafuljs/.github/blob/7402795b3307f1477f002d2bb21c91a360d3f1ab/.github/ISSUE_TEMPLATE/config.yml#L4

**Comment by aralroca** [comment]
Done! Thanks!
