### ISSUE TITLE
TypeScript issues in `v0.11.0`

### ISSUE THREAD

**Issue by filoozom** [teafuljs/teaful#96]
**What version of this package are you using?**

`v0.11.0`

**What operating system, Node.js, and npm version?**

Doesn't matter

**What happened?**

I guess it's mostly that [the `types` in `package.json` points to an inexistant file](https://github.com/teafuljs/teaful/blob/17c88205a10f2c77c4e14dc36d7cd83230cb2344/package.json#L55), or maybe we're missing a build step somewhere?

This makes it so the library can't be used with TypeScript anymore. Build logs. https://github.com/swarmcity/boardwalk-ts/runs/8153017105?check_suite_focus=true

**What did you expect to happen?**

The library should correctly export its types and potentially run a build step before publishing?

**Are you willing to submit a pull request to fix this bug?**

Sure.

**Comment by aralroca** [comment]
@filoozom fix it in 0.11.1
